In [1]:
import pickle
import numpy as np

In [3]:
ohe_sex = pickle.load(open('models/ohe_sex.pkl', 'rb'))
ohe_embarked = pickle.load(open('models/ohe_embarked.pkl', 'rb'))
clf = pickle.load(open('models/clf.pkl', 'rb'))

In [4]:
# Assume user input 
# Pclass/gender/age/sibsp/Fare/Embarked
test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype=object).reshape(1,7)

In [5]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [ ]:
# Here for testing the model , we have to follow the same steps with the input data as we did while training model
# 1. use imputer to handle missing value - no need here since no missing value input
# 2. ohe sex column
# 3. ohe embarked column
# Order should be same as model training - most important

In [9]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))

c:\Users\godsc\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


In [10]:
test_input_sex

array([[0., 1.]])

In [7]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))

In [11]:
test_input_embarked

array([[0., 0., 1.]])

In [12]:
test_input_age = test_input[:,2].reshape(1,1)

In [14]:
# Here the order of conactenation should be same as traing model
test_input_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [15]:
test_input_transformed

array([[2, 0, 0, 10.5, 31.0, 0.0, 1.0, 0.0, 0.0, 1.0]], dtype=object)

In [16]:
clf.predict(test_input_transformed)

array([1], dtype=int64)

* Here we can see the amount of work we have to perform without pipelines
* A single error can malfunction your model